const mongoose=require('mongoose');
const paymentSchema=new mongoose.Schema({
    paymentId:{
        type:String,
    },
    userId:{
        type:mongoose.Types.ObjectId,
        ref:"User",
    },
    orderId:{
        type:String,
        required:true,
    },
    status:{
        type:String,
        required:true,
    },
    amount:{
        type:String,
        required:true,
    },
    currency:{
        type:String,
        required:true,
    },
    receipt:{
        type:String,
        required:true,
    },
    notes:{
        FirstName:{
            type:String,
        },
        LastName:{
            type:String,
        }
    },
},{timestamps:true});
module.exports=mongoose.model("Payment",paymentSchema);